apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-pod
  labels:
    app: nginx
spec:
  containers:
  - name: configmap-volume-pod
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-configmap
      mountPath: "/home"
      readOnly: true
  volumes:
  - name: nginx-configmap
    configMap:
      name: nginx-configmap
