apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: 80-30007
      port: 80 #Port that the SERVICE will expose
      # For convenience, port and the targetport values are set the same.
      targetPort: 80 #Port the POD is listening on. 
      nodePort: 30007 #Port that the NODE will expose. Optional field
