apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
  labels:
    app: nginx
spec:
  containers:
  - name: secret-env-pod
    image: nginx:latest
    ports:
    - containerPort: 80
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: nginx-secret
          key: username
    - name: password
      valueFrom:
        secretKeyRef:
          name: nginx-secret
          key: password
