apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
  labels:
    app: nginx
spec:
  containers:
  - name: secret-volume-pod
    image: nginx:latest
    volumeMounts:
    - name: nginx-secret
      mountPath: "/home"
      readOnly: true
  volumes:
  - name: nginx-secret
    secret:
      secretName: nginx-secret
