apiVersion: v1
kind: Pod
metadata:
  name: super-mario
  labels:
    app: super-mario
spec:
  containers:
  - name: super-mario
    image: pengbai/docker-supermario
    ports:
    - containerPort: 8080
